### ISSUE TITLE
WikidPad not working on Fedora 22

### ISSUE THREAD

**Issue by matysek** [WikidPad/WikidPad#1]
Hi,

I recently upgraded to Fedora 22 but none of wikidpad versions works and just a rectangular window with the wikidpad icon is shown.

Fedora 22 bundles wxPython 3.0.2.0 gtk3 (classic)

With the latest git version I get this output:
```
$ cat ./WikidPad_Error.log    
Version: 'wikidPad 2.3beta13_01' Session start: 2015-06-20 21:50:15
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_boxed_type_register_static: assertion 'g_type_from_name (name) == 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_set_qdata: assertion 'node != NULL' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkWidget'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: cannot register existing type 'GtkBuildable'
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_once_init_leave: assertion 'result != 0' failed
  from gtk import _gtk
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:40: Warning: g_type_register_static: assertion 'parent_type > 0' failed
  from gtk import _gtk
```

Is there anything I could do to get WikidPad working on FC22?

**Comment by ClaudePP** [comment]
It looks to me that the developers are not active anymore. Orphan project? Can someone take over? It is extremly useful piece of software, a pity to close it.

**Comment by matysek** [comment]
Hi @ClaudePP, this is not Orphan project but rather a maintenance fork of https://github.com/butscher/WikidPad 

The original repository seems like not active anymore. Pull request are not reviewed and so on.

I created this project yesterday to give possible contributors a room for cooperation and not depend on original inactive repository.

@ClaudePP If you would like commit access to this repository and contribute directly, let me know.

**Comment by gchriz** [comment]
Should be fixed here too...

**Comment by gchriz** [comment]
PS:
Some messages regarding this issue are here:
https://groups.yahoo.com/neo/groups/wikidPad/conversations/messages/8676
