### ISSUE TITLE
Clear installation instructions for Linux

### ISSUE THREAD

**Issue by ivangretsky** [WikidPad/WikidPad#16]
Good day!

I have used WikidPad for quite while on Windows. Thank you for a great tool!  But now I am on Linux and want to install the program here as well. But cannot find good enough installation instructions. [This one](http://trac.wikidpad2.webfactional.com/wiki/InstallLinux) seems to be outdated and not too clear for a novice user. It does not say neither which version of python should be used nor which dependecies and which versions of those should one use.

As this repo is said to be the official one, maybe here should be some more clear installation instructions in the README or the wiki?

**Comment by spicedreams** [comment]
in principle it's quite simple; you need to install (from your linux distribution's standard package repository) the packages python-wxversion and python-wxgtk3.0. for example:
$ sudo apt install python-wxversion python-wxgtk3.0
Then cd to the folder where wikidpad source is installed, and start it with "python WikidPad.py"
In some cases that will be enough.

But there's something strange that I haven't solved. This is working just fine for me on three machines, and not on two others. Damned if I can see the pattern, though it must be there. On the machines where this doesn't work, I get three warnings from /usr/lib/python2.7/dist-packages/gi/module.py then it just stops.

**Comment by ivangretsky** [comment]
Thanks!
I was hoping to get a link to a .deb file, but your instructions will surely help! Closing this one.
