### ISSUE TITLE
Javascript changes coming from beta15 to beta16

### ISSUE THREAD

**Issue by rzw** [WikidPad/WikidPad#23]
I had a small script within body tags to decode obfuscated email addresses ([https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fromcharcode](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_fromcharcode)).

It worked perfectly in beta 15; no longer in beta 16

**Comment by butscher** [comment]
Could you describe in more detail how and where you inserted it and how you used it?

**Comment by rzw** [comment]
Sure:
I just placed those few lines of script on a normal page within Tags (<body>...</body>) and switched to preview. The "try it" button appears in beta 15.
No button in beta 16, just text.

**Comment by butscher** [comment]
Which OS do you use?

What have you set in options, options page "HTML preview/export", setting "Preview renderer"?

**Comment by rzw** [comment]
Spot on. Thank you so much, Michael.
In beta 15 I had changed the renderer to IE. Unfortunately I hadn't remember that. Also - as always if possible - I chose portable installation. So the settings were all default.

Just for the records: I'm using Windows 10.
