### ISSUE TITLE
Default key binding conflict

### ISSUE THREAD

**Issue by pawelszramowski** [WikidPad/WikidPad#37]
Binding
```python
ActivateLinkNewTab="Ctrl-Alt-L"
```
needs to be removed from file ```extensions\KeyBindings.py``` in order to be enable to input letter Ł using Polish Programmers' keyboard layout (https://en.wikipedia.org/wiki/AltGr_key#Polish).

WikidPad 2.3rc01 on Windows 10.

**Comment by butscher** [comment]
Unfortunately there are too many different languages and keyboard layouts out there to avoid all possible clashes.

To fix this for you, open the WikidPad installation directory (which contains the `extensions` directory and create (if not already there) a `user_extensions` directory. In it create with a text editor a file `KeyBindings.py` (like the one in `extensions`) and insert the line

    ActivateLinkNewTab=""

to disable the problematic shortcut on next start of WikidPad. Alternatively you can also define another shortcut there that better suits your needs.
