### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by cybermcm** [WikidPad/WikidPad#41]
Hi,
Windows version 2.3rc01 portable
I think this bug is related to Windows 10 1809 or another Windows update happened recently. On startup I get an error message:
> Cannot set locale to language Konkani.

My windows is set to English, Region settings set to Austria/German.
I tried other versions too, 2.3 beta15 & 16, same error.
If I use 2.2 -> no error!

Any ideas what setting may cause this?

**Comment by butscher** [comment]
Fixed in latest WikidPad 2.3rc02
