### ISSUE TITLE
[Wiki] All attachments broken

### ISSUE THREAD

**Issue by Losses** [WikidPad/WikidPad#43]
All attachments in WikidPad's wiki are down, returns a 404 page, anyone can fix that?

**Comment by BjornFJohansson** [comment]
I think it would be a good thing to migrate from the trac wiki to the Github wiki for this repo.
It seems this can be done [automatically](https://stackoverflow.com/questions/9710129/how-do-i-export-trac-wiki-to-github-wiki). I do not know about the attached files however, there was never a central repository for plugins AFAIK. 

Are you looking for any plugin in particular?

**Comment by Losses** [comment]
@BjornFJohansson 
I'm looking for this one :<
http://trac.wikidpad2.webfactional.com/wiki/MathJaxPlugin

**Comment by BjornFJohansson** [comment]
That's an old one... Try requesting it on the wikidpad yahoo group, maybe someone still has it.

**Comment by butscher** [comment]
@Losses

As a quick workaround, I have copied the attachments to

http://info.wikidpad2.webfactional.com/attachment/


The attachments on page MathJaxPlugin are available from

http://info.wikidpad2.webfactional.com/attachment/wiki/MathJaxPlugin/

**Comment by butscher** [comment]
Should now work again as expected.

**Comment by Losses** [comment]
@butscher Wow! Thanks!
