### ISSUE TITLE
Zooming by Ctrl + scroll wheel broken in 2.4alpha01

### ISSUE THREAD

**Issue by pawelszramowski** [WikidPad/WikidPad#58]
In wikidPad 2.4alpha01 on Windows 10, zooming by Ctrl + scroll wheel doesn't work anymore and the following entry is added to `WikidPad_Error.log`:
```
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiTxtCtrl.py", line 3507, in OnMouseWheel
AttributeError: 'MouseEvent' object has no attribute 'm_wheelRotation'
```

**Comment by BjornFJohansson** [comment]
Did you change the wxpython version? I remember the changes were made for wp to work 
with the newest wxpython versions.
https://github.com/WikidPad/WikidPad/blob/master/WikidPad/lib/pwiki/WikiTxtCtrl.py#L3504

**Comment by pawelszramowski** [comment]
This happens in the released version (https://github.com/WikidPad/WikidPad/releases/download/WikidPad-2-4-alpha01/WikidPad-2.4alpha01.exe) available for download from http://wikidpad.sourceforge.net/. But you are right, the file you linked was already fixed by https://github.com/WikidPad/WikidPad/commit/3d0990215ce1e11b90e01cf49583ff4a4075cdca, so it's just a matter of releasing a new version.
