### ISSUE TITLE
Feature: Back References

### ISSUE THREAD

**Issue by johannes-z** [WikidPad/WikidPad#64]
Does wikidpad or a plugin already support back references?

What I mean by back references:

Page1 has a Link to Page2. If you open Page2, you have no information which other pages link to Page2. In Latex you usually have back references when quoting literature: The footnote is a link to the bibliography, and there's a link to all footnotes in the bibliography.

**Comment by butscher** [comment]
Such backlinks are called "parents" in WikidPad. The "Navigate" menu has "Go to Parent" to list and open parents of the current page.

**Comment by butscher** [comment]
Such backlinks are called "parents" in WikidPad. The "Navigate" menu has "Go to Parent" to list and open parents of the current page.

**Comment by johannes-z** [comment]
Thanks! This is exactly what I was looking for. Is there a way to also (automatically) add parents to a wiki page's content?
