### ISSUE TITLE
New error on Windows 10: "Can't write to database. Unable to open database file [14]"

### ISSUE THREAD

**Issue by 1984btgn** [WikidPad/WikidPad#73]
I use a few different wikis and this error is coming up for every one. Never happened before, up to a few weeks ago. The 'Reconnect' option under 'Maintenance' gives the same error. Occurs on versions 2.2, 2.3, and 2.4.

From the error log:

> Version: 'wikidPad 2.3rc02' Session start: 2021-02-21 00:19:26
Traceback (most recent call last):
  File "pwiki\wikidata\WikiDataManager.pyo", line 459, in connect
  File "pwiki\wikidata\WikiDataManager.pyo", line 259, in __call__
  File "pwiki\wikidata\original_sqlite\WikiData.pyo", line 207, in connect
DbWriteAccessError: unable to open database file [14]
Traceback (most recent call last):
  File "pwiki\Configuration.pyo", line 508, in save
  File "pwiki\Configuration.pyo", line 274, in save
IOError: [Errno 9] Bad file descriptor

Anyone else having this issue or had any luck solving it?

**Comment by BjornFJohansson** [comment]
Do you use the original sqlite or compact sqlite? For anyone who sees this, never use compact!

**Comment by vashnt707** [comment]
I have been using compact sqlite in Windows for years and faced no issues. Any reason not to use compact? Because it is custom wrapped?

**Comment by 1984btgn** [comment]
@BjornFJohansson I'm using the original sqlite. Under 'About' it says I'm using version 3.6.15.

**Comment by BjornFJohansson** [comment]
@vashnt707 The original sqlite keeps each page as a text file in the file system. In case of corruption, these can always be used to recreate the DB. The compact sqlite file can be corrupted beyond salvation.

**Comment by BjornFJohansson** [comment]
@1984btgn then perhaps rebuild might help? I used to have RAM problems that led to frequent crashes and corruptions. I used to replace the "wikiovw.sli" file with one from an empty db and delete the wikiovw.sli-journal file. Then a rebuild and the wiki is as good as new.

**Comment by 1984btgn** [comment]
@BjornFJohansson Thank you so much for your help. After some more poking around with the issue this morning, I discovered the problem was in Windows Security > Virus & Threat Protection > Ransomware Protection. Windows had stuck the program in read-only mode and not notified me about it. Seems to be working now though. Thanks all! :)
